#let terms = (
  (
    key: "ai",
    short: "AI",
    long: "Artificial Intelligence",
    description: "Field of computer science that focuses on creating systems capable of performing tasks that typically require human intelligence, such as learning, reasoning, problem-solving, and understanding natural language.",
  ),
  (
    key: "black_box",
    short: "black box",
    description: "A term used to describe machine learning models that are complex and not easily interpretable, making it difficult to understand how they arrive at their predictions or decisions.",
  ),
  (
    key: "categorical_features",
    short: "categorical features",
    long: "Categorical Features",
    description: "Features in a dataset that represent discrete categories or groups, rather than continuous numerical values, and often require special handling in machine learning algorithms.",
  ),
  (
    key: "classification",
    long: "Classification",
    description: "A type of machine learning problem in which the goal is to predict discrete class labels based on input features.",
  ),
  (
    key: "cli",
    short: "CLI",
    long: "Command Line Interface",
    description: "A text-based interface that allows users to interact with a computer system by typing commands, rather than using graphical elements.",
  ),
  (
    key: "computational_complexity",
    short: "computational complexity",
    long: "Computational Complexity",
    description: "A measure of the amount of computational resources (time and space) that an algorithm requires to run, often expressed in terms of the size of the input data.",
  ),
  (
    key: "corr_matrix",
    short: "correlation matrix",
    long: "Correlation Matrix",
    description: "A table showing the correlation coefficients between pairs of features in a dataset, used to identify relationships and potential multicollinearity.",
  ),
  (
    key: "explainable ai",
    short: "XAI",
    long: "Explainable Artificial Intelligence",
    description: "A field of artificial intelligence that focuses on creating models and systems that can provide clear and understandable explanations for their decisions and actions.",
  ),
  (
    key: "false positives",
    short: "FP",
    long: "False Positives",
    description: "Instances incorrectly predicted as positive.",
  ),
  (
    key: "false negatives",
    short: "FN",
    long: "False Negatives",
    description: "Instances incorrectly predicted as negative.",
  ),
  (
    key: "gradient descent",
    short: "GD",
    long: "Gradient Descent",
    description: "An optimization algorithm used to minimize the objective function in machine learning models by iteratively adjusting the model's parameters in the direction of the steepest descent.",
  ),
  (
    key: "gui",
    short: "GUI",
    long: "Graphical User Interface",
    description: "A user interface that allows users to interact with a computer system through graphical elements such as windows, icons, and buttons, rather than text-based commands.",
  ),
  (
    key: "large language model",
    short: "LLM",
    long: "Large Language Model",
    longplural: "Large Language Models",
    description: "A type of artificial intelligence model that is trained on vast amounts of text data to understand and generate human-like language.",
  ),
  (
    key: "linear programming",
    short: "LP",
    long: "Linear Programming",
    description: "A mathematical optimization technique used to find the best outcome in a model whose requirements are represented by linear relationships, often used in machine learning for training linear SVMs and other models.",
  ),
  (
    key: "mae",
    short: "MAE",
    long: "Mean Absolute Error",
    description: "A common metric for evaluating the performance of regression models, calculated as the average of the absolute differences between predicted and actual values.",
  ),
  (
    key: "margin",
    short: "margin",
    long: "Margin",
    description: "The distance between the decision boundary (hyperplane) and the closest data points in a Support Vector Machine, which the algorithm seeks to maximize for better generalization.",
  ),
  (
    key: "ml",
    short: "ML",
    long: "Machine Learning",
    description: "A subset of artificial intelligence that involves training algorithms to learn patterns from data and make predictions or decisions without being explicitly programmed.",
  ),
  (
    key: "nystrom method",
    short: "Nyström method",
    description: "A technique used to approximate large kernel matrices in machine learning, which allows for efficient training of models like Support Vector Machines on large datasets by sampling a subset of the data and using it to construct a low-rank approximation of the kernel matrix.",
  ),
  (
    key: "objective_function",
    long: "Objective Function",
    short: "objective function",
    description: "A mathematical function that an algorithm optimizes during training, which defines the goal of the learning process and guides the model's adjustments to minimize error or maximize performance.",
  ),
  (
    key: "outlier",
    short: "outlier",
    description: "A data point that deviates significantly from the majority of the data, which can have a disproportionate influence on machine learning models and may require special handling.",
  ),
  (
    key: "normal_distribution",
    short: "Normal Distribution",
    description: "A continuous probability distribution that is symmetric around its mean, with a bell-shaped curve, and is commonly used in statistics and machine learning to model real-valued random variables.",
  ),
  (
    key: "pca",
    short: "PCA",
    long: "Principal Component Analysis",
    description: "A dimensionality reduction technique that transforms a dataset into a new coordinate system, where the greatest variance by any projection of the data comes to lie on the first coordinate (called the first principal component), the second greatest variance on the second coordinate, and so on, allowing for efficient visualization and analysis of high-dimensional data.",
  ),
  (
    key: "prompt engineering",
    short: "PE",
    long: "Prompt Engineering",
    description: "The process of designing and optimizing prompts to effectively communicate with language models and elicit desired responses.",
  ),
  (
    key: "random fourier features",
    short: "RFF",
    long: "Random Fourier Features",
    description: "A technique used to approximate kernel functions in machine learning, allowing for efficient training of models like Support Vector Machines on large datasets by mapping input data into a higher-dimensional space using random Fourier transformations.",
  ),
  (
    key: "regression",
    long: "Regression",
    description: "A type of machine learning problem in which the goal is to predict continuous numerical values based on input features.",
  ),
  (
    key: "rmse",
    short: "RMSE",
    long: "Root Mean Squared Error",
    description: "A common metric for evaluating the performance of regression models, calculated as the square root of the average of the squared differences between predicted and actual values.",
  ),
  (
    key: "shap",
    short: "SHAP",
    long: "SHapley Additive exPlanations",
    description: "A method for explaining the output of machine learning models by attributing the prediction to each feature.",
  ),
  (
    key: "sequential minimal optimization",
    short: "SMO",
    long: "Sequential Minimal Optimization",
    description: "An algorithm used to solve the optimization problem in Support Vector Machines by breaking it down into smaller subproblems that can be solved analytically, which allows for efficient training of SVMs on large datasets without the need for complex numerical optimization techniques.",
  ),
  (
    key: "stochastic gradient descent",
    short: "SGD",
    long: "Stochastic Gradient Descent",
    description: "An optimization algorithm that updates the model's parameters using a randomly selected subset of the training data, which can lead to faster convergence and better generalization.",
  ),
  (
    key: "true positives",
    short: "TP",
    long: "True Positives",
    description: "Instances correctly predicted as positive.",
  ),
  (
    key: "true negatives",
    short: "TN",
    long: "True Negatives",
    description: "Instances correctly predicted as negative.",
  ),
)